FROM node:22-alpine

WORKDIR /app

# Instalamos la versión exacta de Angular CLI
RUN npm install -g @angular/cli@21.0.0

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]